wxFormBuilder/wxFormBuilder

output/plugins/additional/xml/data.cppcode
output/plugins/additional/xml/data.luacode
output/plugins/additional/xml/data.phpcode
output/plugins/additional/xml/data.xml

Since wxWidgets 3.1 this event has been renamed to `wxEVT_GRID_CELL_CHANGED`. The new name also works with wxWidgets 3.0.

Rename wxEVT_GRID_CELL_CHANGE to wxEVT_GRID_CELL_CHANGED

---

appveyor.yml
build/premake/wxwidgets.lua

This uses [MSYS2](https://msys2.github.io/) to compile, which includes wxWidgets. It even has premake, but for now it's still use the .bat file and therefore the premake4.exe included in git.
The wx-config binary included in wxWidgets is using --rescomp instead of --rcflags. `wx-config --rescomp` returns the full compiler command, e. g.
```sh
$ wx-config --rescomp
windres --include-dir C:/msys64/mingw32/include/wx-3.0 --define __WIN32__ --define __GNUWIN32__
```
That's why I added the `| cut -d' ' -f2-`, to remove the "windres".
These lines
```sh
ln -s /mingw32/include/binutils/bfd.h /mingw32/include/bfd.h
ln -s /mingw32/include/binutils/symcat.h /mingw32/include/symcat.h
ln -s /mingw32/lib/binutils/libbfd.a /mingw32/lib/libbfd.a
ln -s /mingw32/lib/binutils/libiberty.a …
```

Build with AppVeyor CI

---

README.md
appveyor.yml

Package a successful appveyor build as an artifact and add a download link to the README file to allow easy access to current Windows binaries.
This could be expanded to include setups, if they would be built in the appveyor script.

Upload Win32 build as appveyor artifact to allow downloading binaries

---

output/plugins/layout/xml/layout.cppcode
output/plugins/layout/xml/layout.luacode
output/plugins/layout/xml/layout.phpcode
output/plugins/layout/xml/layout.pythoncode
output/plugins/layout/xml/layout.xml
plugins/layout/layout.cpp

Added wxWrapSizer, didn't know what the icon should be

Added wxWrapSizer

---

output/plugins/additional/xml/additional.cppcode

For easier custom control usage and management from wxFormBuilder, the declaration and construction of custom controls can be created with default values, which will probably be just fine in most cases.

Automatic creation of CustomControl declaration and construction

---

output/plugins/common/xml/menutoolbar.pythoncode
output/plugins/forms/xml/forms.pythoncode

A fix for the following deprecation warning  in the generated python code, may be related to 
this [issue](https://github.com/wxFormBuilder/wxFormBuilder/issues/275)
``` 
wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
self.m_menu1.AppendItem( self.m_menuItem1 )
```
And 
```
wxPyDeprecationWarning: Call to deprecated item. Use SetSizeHints instead.
self.SetSizeHintsSz( wx.DefaultSize, wx.DefaultSize )
```

Fix for 2 wxPyDeprecationWarning with the latest wxPython==4.0.0a1

---

output/plugins/layout/xml/layout.pythoncode

Changed 'AddSpacer' to 'Add' as now 'AddSpacer' has only one argument. If it does what I intend for it to do, it should fix #303 and #275.

Updated 'AddSpacer' to new syntax in Phoenix

---

output/plugins/common/xml/menutoolbar.xml
output/plugins/forms/xml/forms.pythoncode
output/xml/default.pythoncode
plugins/common/common.cpp
wxfbTest/wxfbTest.fbp
wxfbTest/wxfbTest_GUI.cpp

I've made a couple changes to correct errors I was getting when using the generated python code. The python code works correctly now, but I'm not sure how to run the built in tests, or if this will effect other code generation. 
Warnings received:
wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
AttributeError: module 'wx' has no attribute 'ST_SIZEGRIP'
Thanks,
Jim

Syntax fixes for SetToolTipString and wxST_SIZEGRIP

---

output/xml/default.xml
src/codegen/cppcg.cpp
src/model/database.cpp
src/model/objectbase.h
src/rad/inspector/objinspect.cpp

Added the ability to change if a subclass is forward declared or the header is included in the generated file. The default is to forward declare it (previous behavior). This included allowing a child property to have a type. Currently only PT_BOOL and PT_WXSTRING are supported

Added the ability to change if a subclass is forward declared or the header is included

---

output/plugins/additional/xml/data.pythoncode
src/codegen/pythoncg.cpp

This mostly consists of adding the wx.dataview prefix. For reference see https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#classic-vs-phoenix for TreeListCtrl at the bottom of the page,

Python CG: Make TreeListCtrl compatible with wxPython Phoenix

---

install/macosx/makedist.sh

Fixes #340 
With these changes, the app bundle produced from travis builds should be actually usable without any manual modifications.
Might also be a fix for #313, although there is no useful info there.

Fix application bundle creation on macOS to produce usable application

---

.travis.yml

- Switches the travis build to use `brew install wxmac --devel`, which now is wxWidgets 3.1.1

Switch travis build for macOS to wxWidgets 3.1

---

src/codegen/luacg.cpp

This fixes the issue #421. The solution was found by looking at the generated code, for some reason unique filtering accross different objects was working, only the filtering in a single object was affected.

Fixes LUA unique include filtering

---

src/rad/inspector/wxfbadvprops.cpp

This fixes the root cause of #419 and #376. The reported crash probably happened because the preview tried to create an icon with these too big garbage values.

Fix garbage ico_size values

---

src/codegen/codewriter.cpp
src/codegen/luacg.cpp
src/md5/md5.cc
src/md5/md5.hh
src/model/database.cpp
src/rad/inspector/objinspect.cpp
src/rad/mainframe.cpp
src/utils/wxfbexception.h

Fixes various warnings reported by MSVC 2015 except wxWidgets deprecation warnings which are handled by #417. Bigger rework of the MD5 class to prevent implicit type conversions.

Fix warnings

---

output/xml/default.xml
src/codegen/cppcg.cpp
src/model/database.cpp
src/rad/inspector/objinspect.cpp

The method used to extract the value of a composed wxPGProperty always returns an empty result, only GenerateComposedValue() does return a value. All locations testing a boolean of such a composed property now use the same approach, compare against the property name. Because of the rather strange storage format of a composed boolean and especially the difference to the format of a non-composed boolean comments about the storage format have been added. Parsing the default values of PT_PARENT child elements from a XML file now works properly with empty child tags.
This should fix at least #436

Fix reading and writing of the subclass element and all other PT_PARENT

---

output/plugins/forms/xml/forms.cppcode
output/plugins/forms/xml/forms.phpcode
output/plugins/forms/xml/forms.pythoncode

This PR brings the Python and PHP code generation templates up to par with the C++ template.
Add arguments `id`, `pos`, `size`, `style` and `name` to the generated constructors for wxPanel forms. Provide the attributes from the project as default values to these constructor arguments.  Pass the arguments down to the respective parent constructor.
* For Python, this fixes #261.
* The PHP and C++ changes have not been tested at runtime, only checked that the generated source files look correct.
* For C++, only the `#ifnotnull $window_name` check is removed, since the default value is correctly declared as `wxEmptyString` in case the attribute was empty.  This is consistent with the other two language implementations.
* I don't know Lua at all and as far as I could tell, the generated code …

Accept additional wxPanel constructor arguments

---

output/plugins/containers/xml/containers.pythoncode

The template code to set the "collapsed" attribute tried to call the
Collapse() method without prepending the object (self).

Fix python code generation for wx.CollapsiblePane.

---

plugins/additional/additional.cpp
plugins/common/common.cpp
plugins/containers/containers.cpp
plugins/forms/forms.cpp
sdk/plugin_interface/plugin.h
src/rad/designer/visualeditor.cpp

Fix assertions because of lost event handlers
The smart trick of the Component base class to pop the event handler if it doesn't match the object does not work because certain wxWidgets elements push event handlers themselves on child objects so this condition cannot be used to determine if the Component itself has pushed one. Remove the cleanup code from the base class and implement it in the derived class instead, this one knows for sure if it has pushed an event handler or not.
NOTE: This introduces an API break, plugins are now required to clean up their pushed event handlers, the base class doesn't do it anymore.

Fix eventhandler

---

src/model/database.cpp
src/rad/mainframe.cpp
src/rad/palette.cpp
src/rad/palette.h

This (re-)enables the ability to change the order of the package tabs (Common, Additional, ...) and store their order in the configuration. I think to remember this have been possible in the past, otherwise i can't explain why this settings is present on my machine, the current code does only read this setting but never write it.
This is quite useful if you use plugins and don't like them to be placed at the end in alphabetical order. This also cleans up the logic by moving this GUI related code fragment to the affected GUI component.

Feature packageorder

---

sdk/plugin_interface/xrcconv.cpp
src/codegen/cppcg.cpp
src/codegen/luacg.cpp
src/codegen/phpcg.cpp
src/codegen/pythoncg.cpp
src/rad/inspector/wxfbadvprops.cpp
src/rad/inspector/wxfbadvprops.h

A new option gets added to the wxFBBitmapProperty to load the bitmap from the XRC system. This allows using [Binary Resource Files](http://docs.wxwidgets.org/trunk/overview_xrc.html). It is up to the application code to initialize the resources. Currently this is only possible for the C++ target because of lack of knowledge if and how the other targets support this.
All other languages return a wxNullBitmap if this method is selected, this is what they already do if one of the other unsupported methods for the language is selected.
This is the second feature of my not-so-private-anymore fork of wxFormBuilder that got rejected in the past because it was only implemented for C++, maybe someone else can verify that the other languages don't support this or can implement this for them if …

Adds the feature to load bitmap resources from XRC

---

output/plugins/common/xml/common.pythoncode

`BitmapComboBox` has been moved from module `combo` to  module `adv `in wxPython version 4.   (https://wxpython.org/Phoenix/docs/html/wx.adv.BitmapComboBox.html#wx.adv.BitmapComboBox). In fact wxPython 4 does not have a `combo` module`.
Also `BitmapComboBox` default `choices` argument should be an empty list `[]` and not an empty string `""`. 
Without both of these changes python code for user interfaces that include `BitmapComboBox` will produce an error when run using wxPython version 4.

Modify python template for BitmapComboBox to comply with changes made in wxPython version 4

---

src/codegen/cppcg.cpp

Only now i discovered that commit 81a138b removes a bug/feature that some of my project files rely on. Before that commit a subclass forward declaration was always done, now it is only done if the subclass also defines a header.
My affected project files use e.g. a book control to which i add pages which are panels but i use the subclass feature to replace these with other classes. These other classes i define further down in the project file so i don't have (and can't if i don't want to depend on the filename of the project) to define a header for them. Because i generate C++ code and the subclasses get declared after the book control this doesn't compile.
This PR restores the behavior to generate forward declarations even with no defined header but only if forward declaration is …

Perform subclass forward declaration even if header is empty

---

output/xml/default.xml
src/codegen/codegen.cpp
src/codegen/codegen.h
src/codegen/cppcg.cpp
src/codegen/cppcg.h
src/codegen/luacg.cpp
src/codegen/luacg.h
src/codegen/phpcg.cpp
src/codegen/phpcg.h
src/codegen/pythoncg.cpp
src/codegen/pythoncg.h

This allows to use names of the form myWidget[0], myWidget[1], ... for objects, multiple dimensions are also allowed. Additionally for C++ an anonymous enum with symbols of the form MYWIDGET_SIZE for single dimensional arrays and MYWIDGET_0_SIZE, MYWIDGET_1_SIZE, ... for multi dimensional arrays are created which store the number of elements in the corresponding dimension.
This change is local to the C++ code generator with one catch that i will explain below.
This is a minimal-change-approach implementation that bases on the fact that declaring a static array and accessing its members is syntactically identical of using a regular member, only special care has to be taken during declaration of the array to declare it only once with the correct dimensions.
The implementation works like …

Add support to use arrays as names of objects

---

src/rad/inspector/objinspect.cpp

The subclass property is currently the only one using this child type, because the only instance using this property, the c++ code generator, interprets a missing value as true and currently no project file update
adds this value if it is missing, the object inspector also needs to interpret a missing value as true to stay in sync.

Interpret a missing child value of type boolean as true

---

output/plugins/layout/xml/layout.xml
plugins/layout/layout.cpp
sdk/plugin_interface/component.h
src/codegen/codegen.cpp
src/model/database.cpp
src/model/objectbase.cpp
src/model/objectbase.h
src/model/types.cpp
src/model/types.h
src/rad/inspector/objinspect.cpp

While fixing the latest sizer related problem i discovered it's still not possible to specify the proportion for growable columns or rows. Turned out it was rather difficult to implement this. The basic problems are that there is no datatype in wxFB for this and limitations of the code template language.
This left me two choices:
1. Create new datatypes
2. Add the Proportions to a second parameter
I quickly dropped the second one because you cannot validate data across two parameters and the code templates needed to be changed (possible with a new language element) and the XRC code too.
So i ended up creating new datatypes that are based on the present intlist types. Because these types do not convert the data between the "stages" XRC<->storage<->display, the new ones don't either because …

Feature growables

---

output/plugins/additional/xml/additional.xml

Changed uint to int for initial property in wxSpinCtrl as it could be negative value.

Fix initial property in wxSpinCtrl

---

output/plugins/layout/xml/layout.cppcode

Closes:  #478 
Sizer itself hasn't an id and can't been bound to event, so need to use inner StaticBox instead.

Fix compile error for wxStaticBoxSizer::OnUpdateUI

---

src/codegen/pythoncg.cpp
src/codegen/pythoncg.h

The feature I implemented in January is currently broken on master.
My initial implementation tried to be smart and only set the m_imagePathWrapperFunctionName member only when absolutely necessary. This proved to be fatal, since maintainers would have to keep track of when to call SetImagePathWrapperFunctionName on the parser (maybe even I already forgot a few places).
I've changed the implementation now so that the PythonTemplateParser constructor receives a new parameter that must be filled by instantiators. This way, the value is passed on to all instances correctly.

Fix python code generation for image wrapper function (#496)

---

src/model/database.cpp

Fixes #561 
Instead of catching exceptions thrown by tinyxml, this code checks first to see if there actually is a lastChild, and if so whether or not the type of child contains a text element.
This requires passing **false** to the calls to **lastChild()**. This tells tinyxml not to throw an exception if there is no lastChild, but rather to return a NULL pointer.

Exceptions

---

plugins/common/common.cpp

Fixes # 562
The only significant issue preventing building **wxFormBuilder** and all plugins as a 64-bit target is issue #562 which refers to storing a pointer into a long.
On my fork I am now able to build and run a 64-bit version of **wxFormBuilder** and all plugin dlls. It does require an additional change to **ImportComponentLibrary** to load the correct version of the dll, however that's going to be dependent on build script changes, so I'm not including that change in this PR. In addition, just because it builds and runs, doesn't mean it's stable, so I want to spend a lot more time working with the 64-bit version before suggesting adding it as an optional build platform.
Note that I did not wrap the changes in bit-depth conditionals. While the change isn't strictly necessary for …

Stores wxObject pointer in a void* instead of a long.

---

src/rad/geninheritclass/GenInheritedDlg.fbp
src/rad/geninheritclass/geninhertclass_gui.cpp
src/rad/geninheritclass/geninhertclass_gui.h

Fixes #570 
Project file is converted by wxFB from version 1.1 to 1.15. Removes the wxALIGN_CENTER_VERTICAL style from the two static text controls that was causing wxWidgets to assert in debug builds. Regenerates the .cpp/.h files.

Updates to version 1.15 of project file.

---

src/rad/mainframe.cpp

This PR enables/disables the Save menu item on the File menu, as well as the Save button on the toolbar based on whether the current project has been modified. It's added to the UpdateFrame() function that handles all the other enable/disable of UI elements.
I'm so used to looking at the Save button to confirm that my current file has been saved, that when I first used **wxFB** I clicked the button multiple times wondering why my project wasn't being saved. Since **wxFB** already does a bunch of enabling/disabling it seemed to make sense to add the code that would bring this in line with common practice (at least on Windows -- I don't know if it's common on OS/X or Unix).

Enables/Disables Save button based on modified state of project file.

---

README.md

win32 builds complain about missing headers for bfd_stdint.h and
diagnostics.h

Add additional header symlinks for win32 build

---

output/xml/default.cppcode
output/xml/default.xml
src/rad/appdata.cpp

It's unlikely that a user will want a precompiled header added to the generated C++ source file, and not want the same precompiled header added to the inherited C++ source file. This PR simply adds the same user-defined preamble to the inherited file(s) that is already added to the generated file(s).

Add cpp_preamble to inherited C++ code

---

src/rad/appdata.cpp
src/rad/appdata.h

Fixes #567 
This changes the message that is displayed when **wxFB** opens an older project file. It states the name of the backup file, and indicates that the new project file will be saved. It then confirms that the backup file was created, and if not, gives the user a choice of retry, skip, cancel.
To see the dialog that is displayed if the copy fails (this assumes that wxfbTest.fbp is still an old version):
- cd to wxfbTest
- copy wxfbTest.fbp to wxfbTest.fbp.bak
- write-protect wxfbTest.fbp.bak
- open wxfbTest.fbp in **wxFB**
Note: This adds a debug-only log message that displays old/new version -- it's there purely for debugging convenience.

Changes UI interaction with user when loading an old project file

---

install/windows/wxFormBuilder.iss

The libzstd.dll is required to open new wxFormBuilder.

Add libzstd to setup.

---

README.md

According to Ubuntu 20.04, these are the packages that are needed now, otherwise you get:
```
E: Package 'libwxgtk3.0-dev' has no installation candidate
E: Unable to locate package libwxgtk-media3.0-dev
E: Couldn't find any package by glob 'libwxgtk-media3.0-dev
```

Package names update in Ubuntu

---

output/plugins/common/xml/menutoolbar.xml
plugins/common/common.cpp
plugins/forms/forms.cpp
src/rad/appdata.cpp

Fixes: #610 
I don't know is there any special code that should be modified after removing property(for clarify warning or something), but I didn't find any so I just removed occurrences.

Remove property label from wxMenuBar

---

output/plugins/additional/xml/data.cppcode
output/plugins/additional/xml/data.luacode
output/plugins/additional/xml/data.phpcode
output/plugins/additional/xml/data.pythoncode
output/plugins/additional/xml/data.xml
plugins/additional/additional.cpp
src/codegen/pythoncg.cpp
src/utils/typeconv.cpp

This PR is for a new feature: To allow `col_label_size` and `row_label_size` in `wxGrid` control to take on their default values, as well as the option `wxGRID_AUTOSIZE`. This fixes issue #355 
To add this feature I converted both properties from "uint" to "editoption".
--------------------------
When I made this conversion I discovered a bug in how "editoption" (`PT_EDIT_OPTION`) was implemented: When the edit value is not one of the valid options, the result should be parsed from the string not 0 as it was. I fixed this bug in a separate, completely independent commit for clarity and to make the code review easier. 
To fix this bug in a modular way, I added a new method `bool    IsMacro(const wxString &str )` to `TypeConv`  that returns whether the current string value of a property …

wxGrid new feature plus bug fix in PT_EDIT_OPTION

---

output/plugins/additional/xml/additional.pythoncode
src/codegen/pythoncg.cpp

This pull requests fixes a bug in python code generation for StyledTextCtrl and MediaCtrl by which the widget's class name was hardcoded during construction which prevented subclassing.

Bug fix in python code generation for StyledTextCtrl and MediaCtrl

---

output/plugins/additional/xml/additional.cppcode
output/plugins/additional/xml/additional.pythoncode
output/plugins/additional/xml/additional.xml

This pull request adds support for the `read_only` property of widget `StyledTextCtrl` to all generators that currently support the StyledTextCtrl widget (currently cpp and python).

Add read_only support to StyledTextCtrl

---

src/codegen/cppcg.cpp

The comment on line 961 which writes the virtual event handlers comment had "overide" instead of "override"

Fixed misspelling in cppcg.cpp

---

src/rad/cpppanel/cpppanel.cpp
src/rad/inspector/objinspect.cpp
src/rad/mainframe.cpp
src/rad/palette.cpp

fix incorrect use of API `wxAuiTabContainer::AddPage` where `wxAuiTabContainer::InsertPage` was intended (4th argument used is the page index, not an image ID). This was uncovered by a wxWidget assertion (`wxFAIL_MSG`) firing in `wxWithImages::GetBitmapBundle(int iconIndex)` in an MSVC wxFormBuilder debug build on MSWindows.
(wxWidgets library version used during test: bleeding edge master branch ~ wxWidgets 3.1.6pre, but going through the wxWidgets history, this seems an older mistake as the 3.1.\* API `wxAuiTabContainer::AddPage()` has not been changed/augmented in any way that I could see would make the existing usage of that API correct. In other words: AFAICT this applies for building against **any wxWidgets 3.1.\* version**.)

fix incorrect use of API `wxAuiTabContainer::AddPage`

---

plugins/common/xml/menutoolbar.cppcode
plugins/common/xml/menutoolbar.phpcode
plugins/common/xml/menutoolbar.pythoncode

This was caused by what looks like bad cut-and-paste in the templates --- the parameter to a #wxparent was removed without removing the #wxparent too. It'd be good if this was more robust.
I've verified that the C++ generated code works, but the PHP and Python was done blindly. At least the codegen doesn't crash any more.
Fixes: #757

Prevent codegen crash when creating drop-down menus.

---

third_party/md5/md5/md5.hh

Build fails with GCC 13 with an error in `md5.hh`:
```
[   78s] In file included from /home/abuild/rpmbuild/BUILD/wxFormBuilder-3.10.1/src/codegen/codewriter.cpp:29:
[   78s] /home/abuild/rpmbuild/BUILD/wxFormBuilder-3.10.1/src/codegen/../md5/md5.hh:51:49: error: 'uint32_t' has not been declared
[   78s]    51 |   void  update     (const unsigned char* input, uint32_t input_length);
[   78s]       |                                                 ^~~~~~~~
[   78s] /home/abuild/rpmbuild/BUILD/wxFormBuilder-3.10.1/src/codegen/../md5/md5.hh:58:49: error: 'uint32_t' has not been declared
[   78s]    58 |   MD5              (const unsigned char* input, uint32_t input_length); // digest string, finalize
[   78s]       |                                                 ^~~~~~~~
[   78s] …
```

Fix build with GCC 13

---

plugins/additional/additional.cpp

Hello,
This should solve issue #474, _wxFormBuilder crash on GNU/Linux when inserting a wxRichTextCtrl component_:
- `wxWidgets-3.0.5.1/src/richtext/richtextbuffer.cpp(4729): assert "partialExtents.GetCount() >= (size_t) range.GetLength()" failed in wxRichTextGetRangeWidth()`
- `wxWidgets-3.2.2.1/src/richtext/richtextbuffer.cpp(4961): assert "partialExtents.GetCount() >= (size_t) range.GetLength()" failed in wxRichTextGetRangeWidth()`
This is the [code line crashing wxFormBuilder](https://github.com/wxFormBuilder/wxFormBuilder/blob/19bcc292a2c535e3bca652520bd43fca43f7f9a0/plugins/additional/additional.cpp#L470):
`r.WriteText(wxT("This line contains tabs:\tFirst tab\tSecond tab\tThird tab"));`
Details of the bug/crash, proposed solution, and environment used are below.
Let me know, thanks. …

Fix wxRichTextCtrl crash on GNU/Linux

---

data/platform/linux/share/applications/org.wxformbuilder.wxFormBuilder.desktop

Debian requires that desktop files have a "Keywords" entry as described here: https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords
This patch add some keywords that I thought were appropriate. Please modify them as you see fit. Thanks.

Add required Keywords to the desktop file.

---

plugins/additional/xml/additional.cppcode
plugins/additional/xml/additional.phpcode
plugins/additional/xml/additional.pythoncode

Hello
There is an issue when multiple timers are declared in wxFormBuilder. All the timers launches the same callback when using the connect method.
Here is a fix for python and cpp.
When using an event table, one has to create manually the IDs (like for controls) to avoid such an issue.
Regards
Cedric

fix multiple timers callback bug

---

plugins/layout/layout.cpp

The wxFlexGridSizer growablerows and growablecols
properties are PT_UINTPAIRLIST, not integers

fix wxFlexGridSizer XRC output of growablerows and growablecols

---

src/codegen/cppcg.cpp
src/codegen/luacg.cpp
src/codegen/phpcg.cpp
src/codegen/pythoncg.cpp
src/rad/inspector/wxfbadvprops.cpp
src/rad/inspector/wxfbadvprops.h

Adds ability to create a bitmap property from SVG resource on Windows or Mac. wxBitmapBundle::FromSVGResource is used for that. The code generation is implemented for C++ only, I am not familiar with wxWidgets library for Python, Lua, etc.

Add 'Load From SVG Resource' for bitmap property

---

plugins/common/common.cpp

When attempting to use a wxTextCtrl with wxTE_MULTILINE, it generates an assertion failure. As wxWidgets documentation says[1], in wxGTK SetMaxLength() may only be used with single line text controls.
[1]: https://docs.wxwidgets.org/3.2/classwx_text_entry.html#a5b9dea0d1adeb9cc14309600de6aff50
Closes: https://github.com/wxFormBuilder/wxFormBuilder/issues/869

Fix assertion failure on multiline wxTextCtrl
