wxFormBuilder/wxFormBuilder

- output/plugins/additional/xml/additional.pythoncode
- output/plugins/common/xml/common.pythoncode
- output/plugins/forms/xml/forms.pythoncode
- src/codegen/pythoncg.cpp
Hi,
I've updated the moved modules in phoenix for python code generation, as per ase1590 #275 request.  I went through all the classes listed here: https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html#modules-which-have-moved
Thanks,
Jim M
> Update for moved modules in phoenix 

- output/plugins/additional/xml/additional.pythoncode
- src/codegen/pythoncg.cpp
Hi,
I've done some changes that work ok locally for python code generation. Tested with both code generation and also event generation.
Best regards,
Iulian
> fixing the python code generation for wxDatePickerCtrl

- .travis.yml
Adapted from: https://docs.travis-ci.com/user/reference/osx/#A-note-on-upgrading-packages
> Don't fail if boost dependency is already up to date

- .travis.yml
Update travis config not to actually destroy the effects of #344 while creating the ZIP archive.
> Fix the zip invocation int travis CI not to replace symlinks with files they link to

- output/xml/default.xml
- src/codegen/codewriter.cpp
- src/codegen/codewriter.h
- src/rad/pythonpanel/pythonpanel.cpp
This commit is to address issue #27 
It's a rather simple fix, but I'm not sure if I thought of everything.
> Python Options (tabs-spaces) #27

- build/premake/wxwidgets.lua
- create_build_files4.bat
> wxMonolithic fix and update bat file for Windows, fix #412

- output/plugins/common/xml/common.cppcode
- output/plugins/common/xml/common.luacode
- output/plugins/common/xml/common.phpcode
- output/plugins/common/xml/common.pythoncode
- plugins/common/common.cpp
Fixes the issues reported here #427 and here #417
> wxButton fixups

- build/premake/plugin-interface.lua
- build/premake/plugins/additional.lua
- build/premake/plugins/common.lua
- build/premake/plugins/containers.lua
- build/premake/plugins/forms.lua
- build/premake/plugins/layout.lua
- build/premake/solution.lua
- build/premake/ticpp.lua
- build/premake/wxformbuilder.lua
- build/premake/wxwidgets.lua
Fix building in debug mode on MSVC and enable building of TiCPP in release mode.
> Fix debugbuild

- .gitignore
Now that i can build in debug mode of course new files appear 😄
> Update ignores to include files generated by MSVC 2015 in debug mode

- src/rad/designer/visualeditor.cpp
This re-enables the commented wxStaticBoxSizer highlight fixes from my ancient patch. I don't know why they were disabled, but they do no harm, im using them for years, and because i use a lot of wxStaticBoxSizers it would be nice to get the highlight working inside them again.
It is rather incovenient to add another special treatment for some element, but i currently don't know how to handle this special case in a more common manner easily. The wxStaticBoxSizer is basically two elements, the invisible sizer and the, in the wxFB object hierary, non-existent visible wxStaticBox. The current data model just can't handle this case.
The wxCollapsiblePane also has broken highlights but there the situation is even more complicated because this element is build up of two visible objects, again …
> Enable the disabled wxStaticBoxSizer highlight fixes

- README.md
As the windows and mac versions haves this i added it for consistency. 
Great project by the way :)
> add missing git clone to linux build and run

- output/plugins/additional/xml/additional.pythoncode
- src/codegen/luacg.cpp
- src/codegen/phpcg.cpp
- src/codegen/pythoncg.cpp
solved problem when calling getPane in wxCollapsePane in Python, PHP and Lua
> wxFB bug with collapsePane

- output/plugins/additional/xml/additional.pythoncode
Insert basic StyledTextEditor for python
> Insert StyledTextEditor for python

- output/plugins/forms/xml/forms.cppcode
> Fix for OnCharHook event

- src/model/database.cpp
- src/model/database.h
Fixes: #287 
wxGridBagSizer has own type so there is need to check if there any other sizers and vice versa when adding wxGridBagSizer.
> Add check when create wxGridBagSizer

- src/codegen/xrccg.cpp
> Update xrc namespace

- build/premake/plugin-interface.lua
- build/premake/plugins/additional.lua
- build/premake/plugins/common.lua
- build/premake/plugins/containers.lua
- build/premake/plugins/forms.lua
- build/premake/plugins/layout.lua
- build/premake/solution.lua
- build/premake/ticpp.lua
- build/premake/wxformbuilder.lua
PR for triggering CI, do not merge if not successful 😄
Note for the future: Branches trigger CI as well, no need to create a PR
> Premake stdupdate

- output/plugins/additional/xml/data.pythoncode
Fix: #601 and fix for setting extra style for property grid itself.
> Update python codegen for wxpropertygrid

- output/plugins/additional/xml/additional.cppcode
- output/plugins/additional/xml/additional.phpcode
- output/plugins/additional/xml/additional.pythoncode
- output/plugins/additional/xml/additional.xml
- plugins/additional/additional.cpp
Fix: #618 
I've not added [property maxlength](https://docs.wxwidgets.org/trunk/overview_xrcformat.html#xrc_wxrichtextctrl) because currently [does nothing](https://docs.wxwidgets.org/trunk/classwx_rich_text_ctrl.html#a3ac4c0377a88864857e678e2bf5a7f14).
> Add wxRichTextCtrl XRC and value property support

- plugins/containers/containers.cpp
> Don't throw exception when import wxScrolledWindow from xrc

- plugins/additional/additional.cpp
> Fix xrc import for wxFile{Dir}PickerControl

- install/windows/wxFormBuilder.iss
Updates the windows installer script to pull in libdeflate and libwebp.
Fixes installer generated by CI to allow installing builds from master.
> Includes additional required dll files in windows installer.

- plugins/containers/containers.cpp
Implements the missing XRC import/export code in plugins/containers/container.cpp.
Fixes #666
> Adds wxSimpleBook XRC export code.

- output/plugins/common/xml/menutoolbar.cppcode
- output/plugins/common/xml/menutoolbar.phpcode
- output/plugins/common/xml/menutoolbar.pythoncode
> Fix misalign for auitoolbar dropdown menu

- .github/workflows/flatpak.yml
- install/linux/flatpak.sh
- install/linux/org.wxformbuilder.wxFormBuilder.json
Because i use another distro, here is a proposal to remove dependency to "dnf".
I also propose to use "flatpak --user" environment, so I can build this on my work-system (without root).
> update flatpak platform to 20.08

- README.md
Tested on latest version msys2 and wxFormBuilder .
> fix Windows (MSYS2) build instruction

- plugins/additional/xml/additional.pythoncode
Update wxHtmlWindow event name mismatch as mentioned in issue #760
> Update additional.pythoncode for wxHtmlWindow Event names

- plugins/additional/additional.cpp
- plugins/common/common.cpp
`<object class="wxButton" name="m_button12">
<label>Replay</label>
<default>0</default>
<auth_needed>0</auth_needed>
<markup>1</markup>
<bitmap>../images/redo.png</bitmap>
<position>wxTOP</position>
</object>`
fix to :
`<object class="wxButton" name="m_button12">
<label>Replay</label>
<default>0</default>
<auth_needed>0</auth_needed>
<markup>1</markup>
<bitmap>../images/redo.png</bitmap>
<bitmapposition>wxTOP</bitmapposition>
</object>`
> fix wxButton property position, export with xrc file

- CHANGELOG.md
- src/codegen/luacg.cpp
> Lua: fixed missing parent name for top level box sizer
